using System.Text.Json;
using NJsonSchema;
using NJsonSchema.CodeGeneration.CSharp;

namespace JKToolKit.CodexSDK.UpstreamGen;

internal static partial class AppServerV2DtoGenerator
{
    private const string RootTypeName = "CodexAppServerV2SchemaRoot";

    public static void Generate(string repoRoot, string schemaPath, string outputRoot)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(repoRoot);
        ArgumentException.ThrowIfNullOrWhiteSpace(schemaPath);
        ArgumentException.ThrowIfNullOrWhiteSpace(outputRoot);

        if (!File.Exists(schemaPath))
        {
            throw new FileNotFoundException($"Schema file not found: {schemaPath}");
        }

        var metadata = UpstreamSchemaDiscovery.GetMetadata(repoRoot, schemaPath);

        var outDir = Path.Combine(outputRoot, "AppServer", "V2");
        Directory.CreateDirectory(outDir);

        DeleteGeneratedCsFiles(outDir);

        var schemaJson = BuildFlattenedV2SchemaJson(schemaPath);
        var schema = JsonSchema.FromJsonAsync(schemaJson).GetAwaiter().GetResult();

        var settings = new CSharpGeneratorSettings
        {
            Namespace = "JKToolKit.CodexSDK.Generated.Upstream.AppServer.V2",
            TypeAccessModifier = "internal",
            PropertySetterAccessModifier = string.Empty,
            GenerateOptionalPropertiesAsNullable = true,
            GenerateNullableReferenceTypes = true,
            GenerateDataAnnotations = false,
            GenerateJsonMethods = false,
            JsonLibrary = CSharpJsonLibrary.SystemTextJson,
            ClassStyle = CSharpClassStyle.Poco
        };

        var generator = new CSharpGenerator(schema, settings);

        // Prime the generator/resolver so GenerateTypes() yields all reachable artifacts.
        _ = generator.GenerateTypes(schema, RootTypeName);

        if (string.Equals(Environment.GetEnvironmentVariable("CODEXSDK_UPSTREAMGEN_DUMP"), "1", StringComparison.Ordinal))
        {
            var combinedPath = Path.Combine(outDir, "__combined.g.cs");
            File.WriteAllText(combinedPath, generator.GenerateFile());
        }

        var artifacts = generator.GenerateTypes()
            .Where(a => !string.Equals(a.TypeName, RootTypeName, StringComparison.Ordinal))
            .OrderBy(a => a.TypeName, StringComparer.Ordinal)
            .ToArray();

        foreach (var artifact in artifacts)
        {
            var code = BuildArtifactFile(settings.Namespace, artifact.Code);
            var fileName = MakeSafeFileName(artifact.TypeName) + ".g.cs";
            var path = Path.Combine(outDir, fileName);
            File.WriteAllText(path, code);
        }

        WriteMissingTypeFixups(outDir, settings.Namespace, artifacts);

        var metadataPath = Path.Combine(outputRoot, "appserver.v2.schema.json");
        File.WriteAllText(metadataPath, JsonSerializer.Serialize(metadata, UpstreamSchemaDiscovery.JsonOptions));
    }

    private static void DeleteGeneratedCsFiles(string outDir)
    {
        foreach (var file in Directory.EnumerateFiles(outDir, "*.cs", SearchOption.TopDirectoryOnly))
        {
            File.Delete(file);
        }
    }

    private static string MakeSafeFileName(string typeName)
    {
        var invalid = Path.GetInvalidFileNameChars();
        return string.Concat(typeName.Select(c => invalid.Contains(c) ? '_' : c));
    }

    private static string BuildArtifactFile(string @namespace, string typeCode)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(@namespace);
        ArgumentException.ThrowIfNullOrWhiteSpace(typeCode);

        return $$"""
// <auto-generated/>
#nullable enable

using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace {{@namespace}};

{{typeCode}}
""";
    }
}
